//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.sayesaman.tut5.cust;

import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.TextView;
import org.sayesaman.R.layout;
import org.sayesaman.database.dao.CustomerDao_;

public final class MyFragment_
    extends MyFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        injectFragmentArguments_();
        dao = CustomerDao_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        tvCode = ((TextView) findViewById(org.sayesaman.R.id.tvCode));
        tvName = ((TextView) findViewById(org.sayesaman.R.id.tvName));
        custImage = ((ImageButton) findViewById(org.sayesaman.R.id.custImage));
        tvId = ((TextView) findViewById(org.sayesaman.R.id.tvId));
        tvAddress = ((TextView) findViewById(org.sayesaman.R.id.tvAddress));
        tvRealName = ((TextView) findViewById(org.sayesaman.R.id.tvRealName));
        {
            View view = findViewById(org.sayesaman.R.id.custImage);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyFragment_.this.custImage();
                    }

                }
                );
            }
        }
        ((CustomerDao_) dao).afterSetContentView_();
        xx();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.tut5_fragment, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static MyFragment_.FragmentBuilder_ builder() {
        return new MyFragment_.FragmentBuilder_();
    }

    private void injectFragmentArguments_() {
        Bundle args_ = getArguments();
        if (args_!= null) {
            if (args_.containsKey("fragmentArgCustId")) {
                try {
                    fragmentArgCustId = args_.getString("fragmentArgCustId");
                } catch (ClassCastException e) {
                    Log.e("MyFragment_", "Could not cast argument to the expected type, the field is left to its default value", e);
                }
            }
        }
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public MyFragment build() {
            MyFragment_ fragment_ = new MyFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

        public MyFragment_.FragmentBuilder_ fragmentArgCustId(String fragmentArgCustId) {
            args_.putString("fragmentArgCustId", fragmentArgCustId);
            return this;
        }

    }

}
