//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.sayesaman.tut5.cust;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.view.ViewPager;
import android.view.KeyEvent;
import android.view.View;
import android.view.Window;
import android.widget.ImageButton;
import android.widget.TextView;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import com.viewpagerindicator.TabPageIndicator;
import org.sayesaman.R.id;
import org.sayesaman.R.layout;
import org.sayesaman.database.dao.CustomerDao_;

public final class PageViewActivity_
    extends PageViewActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.tut5_page);
    }

    private void init_(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN, android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN);
        customer = CustomerDao_.getInstance_(this);
    }

    private void afterSetContentView_() {
        salePathCustQty = ((TextView) findViewById(id.salePathCustQty));
        salePathName = ((TextView) findViewById(id.salePathName));
        salePathId = ((TextView) findViewById(id.salePathId));
        tut5_viewpager = ((ViewPager) findViewById(id.tut5_viewpager));
        tut5_indicator = ((TabPageIndicator) findViewById(id.tut5_indicator));
        salePathImage = ((ImageButton) findViewById(id.salePathImage));
        ((CustomerDao_) customer).afterSetContentView_();
        xx();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, android.view.ViewGroup.LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static PageViewActivity_.IntentBuilder_ intent(Context context) {
        return new PageViewActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, PageViewActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public PageViewActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
