//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.sayesaman.bpp6;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.Window;
import android.widget.TextView;
import org.sayesaman.R.id;
import org.sayesaman.R.layout;
import org.sayesaman.database.dao.CustomerDao_;
import org.sayesaman.database.dao.TourDao_;

public final class MyActivity_
    extends MyActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.bpp6);
    }

    private void init_(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN, android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN);
        customerDao = CustomerDao_.getInstance_(this);
        tourDao = TourDao_.getInstance_(this);
    }

    private void afterSetContentView_() {
        bpp6_header1 = ((TextView) findViewById(id.bpp6_header1));
        bpp6_footer3 = ((TextView) findViewById(id.bpp6_footer3));
        bpp6_header3 = ((TextView) findViewById(id.bpp6_header3));
        bpp6_footer4 = ((TextView) findViewById(id.bpp6_footer4));
        bpp6_footer2 = ((TextView) findViewById(id.bpp6_footer2));
        bpp6_footer5 = ((TextView) findViewById(id.bpp6_footer5));
        bpp6_footer1 = ((TextView) findViewById(id.bpp6_footer1));
        bpp6_header2 = ((TextView) findViewById(id.bpp6_header2));
        bpp6_header4 = ((TextView) findViewById(id.bpp6_header4));
        bpp6_footer6 = ((TextView) findViewById(id.bpp6_footer6));
        ((CustomerDao_) customerDao).afterSetContentView_();
        ((TourDao_) tourDao).afterSetContentView_();
        after();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, android.view.ViewGroup.LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static MyActivity_.IntentBuilder_ intent(Context context) {
        return new MyActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MyActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MyActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
