//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.sayesaman.bpp4.updatechecker;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.Window;
import android.widget.Button;
import android.widget.TextView;
import org.sayesaman.R.id;
import org.sayesaman.R.layout;
import org.sayesaman.database.DatabaseHandler;
import org.sayesaman.database.dao.ConfigDao_;

public final class UpdateActivity_
    extends UpdateActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.bpp4);
    }

    private void init_(Bundle savedInstanceState) {
        handler = ((DatabaseHandler) this.getApplication());
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN, android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN);
        dao = ConfigDao_.getInstance_(this);
    }

    private void afterSetContentView_() {
        bpp4_server_address_ = ((TextView) findViewById(id.bpp4_server_address_));
        bpp4_new_testing_remove = ((Button) findViewById(id.bpp4_new_testing_remove));
        bpp4_btn_update = ((Button) findViewById(id.bpp4_btn_update));
        bpp4_server_address = ((TextView) findViewById(id.bpp4_server_address));
        bpp4_version_code_ = ((TextView) findViewById(id.bpp4_version_code_));
        bpp4_version_code = ((TextView) findViewById(id.bpp4_version_code));
        bpp4_new_testing_add = ((Button) findViewById(id.bpp4_new_testing_add));
        {
            View view = findViewById(id.bpp4_btn_update);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        UpdateActivity_.this.bpp4_btn_update();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.bpp4_new_testing_add);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        UpdateActivity_.this.bpp4_new_testing_add();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.bpp4_new_testing_remove);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        UpdateActivity_.this.bpp4_new_testing_remove();
                    }

                }
                );
            }
        }
        ((ConfigDao_) dao).afterSetContentView_();
        after();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, android.view.ViewGroup.LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static UpdateActivity_.IntentBuilder_ intent(Context context) {
        return new UpdateActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, UpdateActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public UpdateActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
