//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.sayesaman.tut4.path;

import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.TextView;
import org.sayesaman.R.layout;
import org.sayesaman.database.dao.SalePathDao_;

public final class FragmentSalePath_
    extends FragmentSalePath
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        injectFragmentArguments_();
        dao = SalePathDao_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        salePathName = ((TextView) findViewById(org.sayesaman.R.id.salePathName));
        salePathImage = ((ImageButton) findViewById(org.sayesaman.R.id.salePathImage));
        salePathId = ((TextView) findViewById(org.sayesaman.R.id.salePathId));
        salePathCustQty = ((TextView) findViewById(org.sayesaman.R.id.salePathCustQty));
        {
            View view = findViewById(org.sayesaman.R.id.salePathImage);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        FragmentSalePath_.this.salePathImage();
                    }

                }
                );
            }
        }
        ((SalePathDao_) dao).afterSetContentView_();
        after();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.tut4_fragment, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static FragmentSalePath_.FragmentBuilder_ builder() {
        return new FragmentSalePath_.FragmentBuilder_();
    }

    private void injectFragmentArguments_() {
        Bundle args_ = getArguments();
        if (args_!= null) {
            if (args_.containsKey("fragmentArgSalePathId")) {
                try {
                    fragmentArgSalePathId = args_.getString("fragmentArgSalePathId");
                } catch (ClassCastException e) {
                    Log.e("FragmentSalePath_", "Could not cast argument to the expected type, the field is left to its default value", e);
                }
            }
            if (args_.containsKey("fragmentArgSalePathQty")) {
                try {
                    fragmentArgSalePathQty = args_.getString("fragmentArgSalePathQty");
                } catch (ClassCastException e) {
                    Log.e("FragmentSalePath_", "Could not cast argument to the expected type, the field is left to its default value", e);
                }
            }
            if (args_.containsKey("fragmentArgSalePathName")) {
                try {
                    fragmentArgSalePathName = args_.getString("fragmentArgSalePathName");
                } catch (ClassCastException e) {
                    Log.e("FragmentSalePath_", "Could not cast argument to the expected type, the field is left to its default value", e);
                }
            }
        }
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public FragmentSalePath build() {
            FragmentSalePath_ fragment_ = new FragmentSalePath_();
            fragment_.setArguments(args_);
            return fragment_;
        }

        public FragmentSalePath_.FragmentBuilder_ fragmentArgSalePathId(String fragmentArgSalePathId) {
            args_.putString("fragmentArgSalePathId", fragmentArgSalePathId);
            return this;
        }

        public FragmentSalePath_.FragmentBuilder_ fragmentArgSalePathQty(String fragmentArgSalePathQty) {
            args_.putString("fragmentArgSalePathQty", fragmentArgSalePathQty);
            return this;
        }

        public FragmentSalePath_.FragmentBuilder_ fragmentArgSalePathName(String fragmentArgSalePathName) {
            args_.putString("fragmentArgSalePathName", fragmentArgSalePathName);
            return this;
        }

    }

}
