//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.sayesaman.app7;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.Window;
import android.widget.ImageView;
import android.widget.TextView;
import org.sayesaman.R.id;
import org.sayesaman.R.layout;
import org.sayesaman.database.dao.CustomerDao_;
import org.sayesaman.database.dao.TourDao_;

public final class MyActivity_
    extends MyActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.app7);
    }

    private void init_(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN, android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN);
        customerDao = CustomerDao_.getInstance_(this);
        tourDao = TourDao_.getInstance_(this);
    }

    private void afterSetContentView_() {
        app7_nahieh_ = ((TextView) findViewById(id.app7_nahieh_));
        app7_tarikh_visit_ = ((TextView) findViewById(id.app7_tarikh_visit_));
        app7_zayeat_max_ = ((TextView) findViewById(id.app7_zayeat_max_));
        app7_sarparast_ = ((TextView) findViewById(id.app7_sarparast_));
        app7_tedad_moshtari_kol_ = ((TextView) findViewById(id.app7_tedad_moshtari_kol_));
        app7_mantaghe_ = ((TextView) findViewById(id.app7_mantaghe_));
        app7_mablagh_darkhast_min_ = ((TextView) findViewById(id.app7_mablagh_darkhast_min_));
        app7_masir_asli_ = ((TextView) findViewById(id.app7_masir_asli_));
        app7_kanal_vizitor_ = ((TextView) findViewById(id.app7_kanal_vizitor_));
        app7_vizitor_ = ((TextView) findViewById(id.app7_vizitor_));
        app7_narmafzar_ = ((TextView) findViewById(id.app7_narmafzar_));
        app7_sakhtafzar_ = ((TextView) findViewById(id.app7_sakhtafzar_));
        app7_user = ((ImageView) findViewById(id.app7_user));
        app7_shomare_toor_ = ((TextView) findViewById(id.app7_shomare_toor_));
        app7_darkhast_kharej_masir_no_ = ((TextView) findViewById(id.app7_darkhast_kharej_masir_no_));
        ((CustomerDao_) customerDao).afterSetContentView_();
        ((TourDao_) tourDao).afterSetContentView_();
        after();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, android.view.ViewGroup.LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static MyActivity_.IntentBuilder_ intent(Context context) {
        return new MyActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MyActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MyActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
