//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.sayesaman.app2;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.Window;
import android.widget.ImageView;
import org.sayesaman.R.id;
import org.sayesaman.R.layout;
import org.sayesaman.database.DatabaseHandler;

public final class MainActivity_
    extends MainActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.app2);
    }

    private void init_(Bundle savedInstanceState) {
        handler = ((DatabaseHandler) this.getApplication());
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN, android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN);
    }

    private void afterSetContentView_() {
        app2_btn07 = ((ImageView) findViewById(id.app2_btn07));
        app2_btn14 = ((ImageView) findViewById(id.app2_btn14));
        app2_btn17 = ((ImageView) findViewById(id.app2_btn17));
        app2_btn09 = ((ImageView) findViewById(id.app2_btn09));
        app2_btn18 = ((ImageView) findViewById(id.app2_btn18));
        app2_btn03 = ((ImageView) findViewById(id.app2_btn03));
        app2_btn01 = ((ImageView) findViewById(id.app2_btn01));
        app2_btn11 = ((ImageView) findViewById(id.app2_btn11));
        app2_btn02 = ((ImageView) findViewById(id.app2_btn02));
        app2_btn06 = ((ImageView) findViewById(id.app2_btn06));
        app2_btn10 = ((ImageView) findViewById(id.app2_btn10));
        app2_btn04 = ((ImageView) findViewById(id.app2_btn04));
        app2_btn05 = ((ImageView) findViewById(id.app2_btn05));
        app2_btn19 = ((ImageView) findViewById(id.app2_btn19));
        app2_btn15 = ((ImageView) findViewById(id.app2_btn15));
        app2_btn08 = ((ImageView) findViewById(id.app2_btn08));
        app2_btn12 = ((ImageView) findViewById(id.app2_btn12));
        app2_btn13 = ((ImageView) findViewById(id.app2_btn13));
        app2_btn16 = ((ImageView) findViewById(id.app2_btn16));
        {
            View view = findViewById(id.app2_btn01);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn01();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn02);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn02();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn08);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn08();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn04);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn04();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn13);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn13();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn07);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn07();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn05);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn05();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn16);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn16();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn06);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn06();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn03);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn03();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn09);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn09();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn15);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn15();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn10);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn10();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn11);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn11();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn19);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn19();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn18);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn18();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn12);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn12();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn14);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn14();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app2_btn17);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.app2_btn17();
                    }

                }
                );
            }
        }
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, android.view.ViewGroup.LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static MainActivity_.IntentBuilder_ intent(Context context) {
        return new MainActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MainActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MainActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
