//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.sayesaman.app9.config;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.Window;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.TextView;
import org.sayesaman.R.id;
import org.sayesaman.R.layout;
import org.sayesaman.database.dao.ConfigDao_;

public final class MyActivity_
    extends MyActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.app9);
    }

    private void init_(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN, android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN);
        dao = ConfigDao_.getInstance_(this);
    }

    private void afterSetContentView_() {
        app9_web_part3 = ((EditText) findViewById(id.app9_web_part3));
        app9_web_part2 = ((EditText) findViewById(id.app9_web_part2));
        app9_my_place_ = ((TextView) findViewById(id.app9_my_place_));
        app9_web_port = ((EditText) findViewById(id.app9_web_port));
        app9_local_port = ((EditText) findViewById(id.app9_local_port));
        app9_web_part1 = ((EditText) findViewById(id.app9_web_part1));
        app9_local_part1 = ((EditText) findViewById(id.app9_local_part1));
        app9_my_place = ((CheckBox) findViewById(id.app9_my_place));
        app9_web_ = ((TextView) findViewById(id.app9_web_));
        app9_local_part2 = ((EditText) findViewById(id.app9_local_part2));
        app9_btn_save = ((Button) findViewById(id.app9_btn_save));
        app9_local_ = ((TextView) findViewById(id.app9_local_));
        app9_web_part4 = ((EditText) findViewById(id.app9_web_part4));
        app9_btn_cancel = ((Button) findViewById(id.app9_btn_cancel));
        app9_local_part3 = ((EditText) findViewById(id.app9_local_part3));
        app9_local_part4 = ((EditText) findViewById(id.app9_local_part4));
        {
            View view = findViewById(id.app9_btn_cancel);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyActivity_.this.app9_btn_cancel();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.app9_btn_save);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyActivity_.this.app9_btn_save();
                    }

                }
                );
            }
        }
        ((ConfigDao_) dao).afterSetContentView_();
        after();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, android.view.ViewGroup.LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static MyActivity_.IntentBuilder_ intent(Context context) {
        return new MyActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MyActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MyActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
